/**
 * Copyright © 2014, Oracle and/or its affiliates. All rights reserved.
 *
 * JDK 8 MOOC Lesson 3 homework
 */
package lesson3;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.stream.Collectors;

/**
 * @author Simon Ritter (@speakjava)
 * @author Stuart Marks
 */
public class Lesson3 {
  /* How many times to repeat the test.  5 seems to give reasonable results */
  private static final int RUN_COUNT = 5;
  
  /**
   * Used by the measure method to determine how long a Supplier takes to
   * return a result.
   *
   * @param <T> The type of the result provided by the Supplier
   * @param label Description of what's being measured
   * @param supplier The Supplier to measure execution time of
   * @return
   */
  static <T> T measureOneRun(String label, Supplier<T> supplier) {
    long startTime = System.nanoTime();
    T result = supplier.get();
    long endTime = System.nanoTime();
    System.out.printf("%s took %dms%n",
        label, (endTime - startTime + 500_000L) / 1_000_000L);
    return result;
  }

  /**
   * Repeatedly generate results using a Supplier to eliminate some of the
   * issues of running a micro-benchmark.
   *
   * @param <T> The type of result generated by the Supplier
   * @param label Description of what's being measured
   * @param supplier The Supplier to measure execution time of
   * @return The last execution time of the Supplier code
   */
  static <T> T measure(String label, Supplier<T> supplier) {
    T result = null;

    for (int i = 0; i < RUN_COUNT; i++)
      result = measureOneRun(label, supplier);

    return result;
  }

  /**
   * Computes the Levenshtein distance between every pair of words in the
   * subset, and returns a matrix of distances. This actually computes twice as
   * much as it needs to, since for every word a, b it should be the case that
   * lev(a,b) == lev(b,a) i.e., Levenshtein distance is commutative.
   *
   * @param wordList The subset of words whose distances to compute
   * @param parallel Whether to run in parallel
   * @return Matrix of Levenshtein distances
   */
  static int[][] computeLevenshtein(List<String> wordList, boolean parallel) {
    final int LIST_SIZE = wordList.size();
    final int[][] distances = new int[LIST_SIZE][LIST_SIZE];
    
    // for faster access
    final String[] arrWordList = new String[LIST_SIZE];
    wordList.toArray(arrWordList);

    // generate list of permutations using imperative programming
    List<Consumer<int[][]>> consumers = new ArrayList<>(LIST_SIZE * LIST_SIZE);
    for (int i = 0; i < LIST_SIZE; i++) {
      for (int j = 0; j < LIST_SIZE; j++) {
        final int _i = i;
        final int _j = j;
        consumers.add(t -> t[_i][_j] = Levenshtein.lev(arrWordList[_i], arrWordList[_j]));
      }
    }

    (parallel ? consumers.parallelStream() : consumers.stream())
      .forEach(t -> t.accept(distances));

    return distances;
  }
  
  /**
   * Process a list of random strings and return a modified list
   * 
   * @param wordList The subset of words whose distances to compute
   * @param parallel Whether to run in parallel
   * @return The list processed in whatever way you want
   */
  static List<String> processWords(List<String> wordList, boolean parallel) {
    return (parallel ? wordList.parallelStream() : wordList.stream())
      .filter(w -> w.length() % 2 == 0)
      .map(String::toLowerCase)
      .sorted()
      .distinct()
      .collect(Collectors.toList());
  }

  /**
   * Main entry point for application
   *
   * @param args the command line arguments
   * @throws IOException If word file cannot be read
   */
  public static void main(String[] args) throws IOException {
    RandomWords fullWordList = new RandomWords();
    
    List<String> wordList = fullWordList.createList(1000);
    measure("Sequential", () -> computeLevenshtein(wordList, false));
    measure("Parallel", () -> computeLevenshtein(wordList, true));
  
    List<String> wordList2 = fullWordList.allWords();    
    measure("Sequential", () -> processWords(wordList2, false));
    measure("Parallel", () -> processWords(wordList2, true));
  }
}